#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=3
umask 077
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ENV_FILE="${BOTHARNESS_IM_TEST_APPS_ENV:-$(node -p "require('node:path').join(require('node:os').homedir(), '.config', 'botharness', 'im-test-apps.env').replaceAll(String.fromCharCode(92), '/')")}"
node "$SCRIPT_DIR/dev-im-test-apps.mjs" protect "$ENV_FILE"
touch "$ENV_FILE"
chmod 600 "$ENV_FILE"
# Keep write_env's replacement files inside the protected shared directory.
export TMPDIR="$(dirname "$ENV_FILE")"

banner "BotHarness 独立 Lark 测试 App 配置"

stage "选择固定测试槽与独立 App"
say "使用 QA1、QA2 或 QA3 固定槽；每个槽只对应一个独立测试 App。跨 worktree、branch 和 session 复用，不必重新创建。"
say "再次运行时按 Enter 保留现有名称和凭据；历史空闲确认不代表当前窗口。"
say "本向导不启动接收器、不停止其他 Host、不配置生产 App。"
open_url "https://open.larksuite.com/app"
step "扫码登录，选择已有独立测试 App；或创建 Company-built app。"
step "不要复用已有活跃任务的 Onboarding QA #824，也不要选择生产 DeepSeekBot。"
ask BH_IM_QA_SLOT "测试槽 [QA1/QA2/QA3]:"
[[ "$BH_IM_QA_SLOT" =~ ^QA[123]$ ]] || { warn "槽必须为 QA1、QA2 或 QA3。"; exit 1; }
prefix="BH_LARK_${BH_IM_QA_SLOT}"
ask "${prefix}_NAME" "App 的控制台显示名称:"
name_key="${prefix}_NAME"
[[ -n "${!name_key}" && ! "${!name_key}" =~ [[:cntrl:]] ]] || { warn "App 名称不能包含控制字符；请重新输入。"; exit 1; }
confirm "确认这是独立测试 App，并且当前没有任何其他接收器运行？" || exit 1
write_env BH_IM_QA_SLOT "$BH_IM_QA_SLOT"
write_env "$name_key" "${!name_key}"
write_env "${prefix}_DOMAIN" "lark"
# An operator statement, not an automatic lock or continuing receiver lease.
write_env "${prefix}_RECEIVER_CHECKED_AT" "$(date -u +%Y-%m-%dT%H:%M:%SZ)"

stage "私密保存 App 凭据"
open_url "https://open.larksuite.com/app"
step "进入所选 App → Credentials & Basic Info。App ID 与 App Secret 必须来自同一 App。"
ask "${prefix}_APP_ID" "复制 App ID（cli_ 开头）:"
id_key="${prefix}_APP_ID"
[[ "${!id_key}" =~ ^cli_[A-Za-z0-9_-]+$ ]] || { warn "App ID 格式无效。"; exit 1; }
ask_secret "${prefix}_APP_SECRET" "复制 App Secret（隐藏输入）:"
secret_key="${prefix}_APP_SECRET"
[[ "${!secret_key}" =~ ^[A-Za-z0-9_-]+$ ]] || { warn "App Secret 为空或格式无效。"; exit 1; }
write_env "$id_key" "${!id_key}"
write_env "$secret_key" "${!secret_key}"
chmod 600 "$ENV_FILE"
note "凭据仅保存在机器本地；请勿 source 此文件（名称可能含空格）。由配置加载器按键值读取。"

stage "核对 Bot、最小权限和消息事件"
open_url "https://open.larksuite.com/app/${!id_key}"
step "Add Features → 添加 Bot 能力。"
step "Permissions & Scopes → Tenant token：核对群 @ 接收 im:message.group_at_msg:readonly、发送 im:message:send_as_bot 和读取 im:message:readonly。"
step "DM 接收权限以消息事件页面当前列出的应用身份权限为准。普通群消息和完整群历史权限不属于本次最小配对验证。"
open_url "https://open.larksuite.com/document/server-docs/im-v1/message/events/receive"
step "Events & Callbacks → Event Configuration：使用 Persistent connection，订阅 im.message.receive_v1。"
note "若平台要求已建立长连接后才能保存事件：先保存此配置，等本次隔离 Host 就绪后完成事件步骤。不要临时启动第二个 SDK receiver。"
step "Version Management & Release → 创建并发布测试版本，完成组织审批与测试用户可用范围。"
step "把应用 Bot 加入专用测试群；使用你的正常 Lark 客户端发送后续真实 DM/群 @。"
if confirm "上述配置已完成并发布？"; then
  write_env "${prefix}_CONSOLE_READY" "yes"
else
  write_env "${prefix}_CONSOLE_READY" "pending"
  SKIPPED+=("完成长连接事件配置、测试版本发布与测试群添加")
fi
say "完成后告诉代理所选 QA 槽；无需发送 App Secret。启动前仍须重新核验接收器独占。"
finish
